Add docs on how to run the stdlib unit tests
inko-lang/inko pull request #515
Opened 2023-03-31 12:43 UTC by dusty-phillips

I thought there might be a script or make target for this, but I didn't see one. The instructions given are what I did to puzzle through it, but I'm not sure they are the best instructions. Happy to improve if there is a better way to do it.

2023-03-31 20:40 UTC, yorickpeterse commented on docs/source/guides/contributing.md
> +* Run the built inko tests `../target/release/inko test`
The following steps make this a bit easier:

> 1. Enter the standard library directory using `cd libstd`
> 2. Run the tests using `cargo run -p inko --release -- test`

This way any Rust related changes are picked up right away.

2023-04-01 13:55 UTC, yorickpeterse commented
One small note about the commit message: right now the description is aimed towards those reviewing the changes in this PR (e.g. bits such as "Happy to improve if there is a better way to do it."). It's better to describe what is done, what the thought behind it is. In this case the changes are simple enough such that the commit body can just be removed entirely.

2023-04-01 13:55 UTC, yorickpeterse requested changes

2023-04-01 13:55 UTC, yorickpeterse commented on docs/source/guides/contributing.md
> +| inko-lang/website  | The Inko website          | <https://github.com/inko-lang/website/issues>  |
These changes are unnecessary, as they're not related to the rest and the trailing `|` isn't needed in Markdown tables.

2023-04-01 13:55 UTC, yorickpeterse commented on docs/source/guides/contributing.md
> +requests for issues labelled as "Accepting contributions".
This too isn't necessary, and I think even incorrect given the syntax description at https://squidfunk.github.io/mkdocs-material/reference/admonitions/.

2023-04-01 17:43 UTC, dusty-phillips commented
Oops, sorry about that. Vim auto-formatted the file for me and I forgot to `:noa`.

2023-04-02 14:49 UTC, yorickpeterse approved these changes

2023-04-02 14:50 UTC, merged

2023-04-02 14:51 UTC, yorickpeterse commented
@dusty-phillips Thanks! :tada: