Run "pkg sync" before running "inko build" if needed
inko-lang/inko pull request #742
Opened 2024-08-10 18:46 UTC by uasi

Closes https://github.com/inko-lang/inko/issues/722

Followed all steps described in #722.

2024-08-10 20:25 UTC, yorickpeterse requested changes
Overall this looks great, just a few small comments :smiley:

2024-08-10 20:25 UTC, yorickpeterse commented on inko/src/pkg/sync.rs
> +    }
I think this check isn't needed. This method is only called in `sync()`, which in turn is only called if either `inko.pkg` changed (meaning it must exist in the first place), or if one runs `inko pkg sync`.

I think what we can do is the following:

We change `manifest_hash` such that if `read()` returns an error, we check if that error is `std::io::ErrorKind::NotFound`. If so, we return `Ok(None)`. For any other error we return `Err(String)`. If the file does exist, we return `Ok(Some(the hash))`.

In `save_manifest_hash` we then call `manifest_hash`, and if it returns `Ok(None)` we just return early. This way we don't need the extra `exists()` check.

2024-08-10 20:28 UTC, yorickpeterse commented
Oh I forgot to add: we should also call `sync_if_needed` when running the following commands:

- `inko check`
- `inko doc`
- `inko test`

2024-08-11 06:15 UTC, uasi commented on inko/src/pkg/sync.rs
> +        // had a manifest file but deleted it when it was no longer needed.
> the user once had a manifest file but deleted it when it was no longer needed

In this case, empty inko.pkg will be re-created on running pkg sync.

2024-08-13 19:21 UTC, yorickpeterse approved these changes

2024-08-13 19:21 UTC, merged

2024-08-13 19:21 UTC, yorickpeterse commented
@uasi Thanks! :tada: